site_name: Tom's Graduation Portfolio
nav:
    - Home: 'index.md'
    - Learning Impacts:
        - Connected Learner: 'impacts/cl.md'
        - Critical Thinker: 'impacts/crit.md'
        - Creative Thinker: 'impacts/cret.md'
        - Purposeful Doer: 'impacts/pd.md'
    - Portfolio Defense: 'defense.md'
